auto: true
permalink: /posts/:title
author: Bruno Pinto
name: Bruno Pinto
description: Writings by Bruno Pinto. Bruno works at ThoughtWorks and enjoys drinking beer.
url: http://bpinto.github.com
markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments: true
